In [18]:
import numpy as np
import pandas as pd


In [9]:
a = np.arange(5)

In [10]:
a.max()

4

In [11]:
a.min()

0

In [12]:
np.linspace(0,8,10)

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

In [13]:
np.random.rand(1,2)

array([[0.56477399, 0.35034035]])

In [14]:
np.random.randint(1,5)

2

In [15]:
np.random.randn(4,5)

array([[-0.71840017,  0.53855699,  1.02954648,  2.23368131,  0.07523689],
       [ 2.04768242, -0.52031221, -0.62806304, -1.86576128, -0.07704627],
       [ 0.12880146, -0.0294262 ,  0.19551091, -0.16491723,  0.32418643],
       [-0.75080761, -0.78071398,  1.2664505 , -0.00816034, -0.1480073 ]])

TypeError: 'module' object is not callable

In [20]:
np.random.seed(101)

In [23]:
df =pd.DataFrame(randn(5,5),index='A,B,C,D,E'.split(),columns='W,X,Y,Z'.split())

NameError: name 'randn' is not defined